services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: zebra_app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            - APP_ENV=local
            - APP_DEBUG=true

    db:
        image: postgres:16
        container_name: zebra_db
        environment:
            POSTGRES_DB: zebra_test
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ybrbnf12
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
