version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: zebra_app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: postgres:14
        container_name: zebra_db
        environment:
            POSTGRES_DB: zebra
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
